/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab99;

import static com.mycompany.lab99.Group.deleteGroup;
import static com.mycompany.lab99.Group.demoteFromAdmin;
import static com.mycompany.lab99.Group.editGroupPost;
import static com.mycompany.lab99.Group.leaveGroup;
import static com.mycompany.lab99.Group.promoteToAdmin;
import static com.mycompany.lab99.Group.removePostFromGroup;
import static com.mycompany.lab99.Group.removeUserFromGroup;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Victus
 */
public class CreatorGroup extends javax.swing.JFrame {

    /**
     * Creates new form CreatorGroup
     */
        Group group;

    public CreatorGroup(Group g) {
        initComponents();
        group=g;
        updateData();
    }
  public void updateData(){
        GroupName.setText(group.getGroupName());
        String path;
        path=group.getPhotoPath();
        ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage();
            Image scaledImg = img.getScaledInstance(230, 88, Image.SCALE_DEFAULT);
            GroupPhotoLabel.setIcon(new ImageIcon(scaledImg));
            ArrayList<Post> posts=group.getPosts();
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    for (Post post : posts) {
            listModel.addElement(post.getContent());
        }
                    GroupPostsList.setModel(listModel);
                    DefaultListModel<String> listModel2 = new DefaultListModel<>();
ArrayList<String>a=group.getUserIds();
         for (String string : a) {
             listModel2.addElement(string);
         }
         GroupMembersList.setModel(listModel2);
    }
  private CreatorGroup(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddPostBtn = new javax.swing.JButton();
        GroupPhotoLabel = new javax.swing.JLabel();
        LeaveGroup = new javax.swing.JButton();
        ViewPostBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        GroupMembersList = new javax.swing.JList<>();
        backBtn = new javax.swing.JButton();
        RemoveMemberBtn = new javax.swing.JButton();
        GroupName = new javax.swing.JLabel();
        refresshBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DeletePostBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EditPostBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        GroupPostsList = new javax.swing.JList<>();
        ViewProf = new javax.swing.JButton();
        PromoteMember = new javax.swing.JButton();
        DemoteMember = new javax.swing.JButton();
        DeleteGroupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Group posts:");

        AddPostBtn.setBackground(new java.awt.Color(255, 0, 204));
        AddPostBtn.setText("Add post");
        AddPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPostBtnActionPerformed(evt);
            }
        });

        LeaveGroup.setBackground(new java.awt.Color(255, 0, 204));
        LeaveGroup.setText("Leave group");
        LeaveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveGroupActionPerformed(evt);
            }
        });

        ViewPostBtn.setText("View Post");
        ViewPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPostBtnActionPerformed(evt);
            }
        });

        GroupMembersList.setBackground(new java.awt.Color(255, 51, 204));
        GroupMembersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(GroupMembersList);

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        RemoveMemberBtn.setText("remove member");
        RemoveMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMemberBtnActionPerformed(evt);
            }
        });

        refresshBtn.setText("refresh");
        refresshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresshBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Group name:");

        DeletePostBtn.setText("Delete Post");
        DeletePostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePostBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("group member:");

        EditPostBtn.setText("Edit post");
        EditPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPostBtnActionPerformed(evt);
            }
        });

        GroupPostsList.setBackground(new java.awt.Color(255, 51, 204));
        GroupPostsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(GroupPostsList);

        ViewProf.setText("view profile");
        ViewProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfActionPerformed(evt);
            }
        });

        PromoteMember.setText("Promote member");
        PromoteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoteMemberActionPerformed(evt);
            }
        });

        DemoteMember.setText("Demote admin");
        DemoteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoteMemberActionPerformed(evt);
            }
        });

        DeleteGroupBtn.setBackground(new java.awt.Color(153, 255, 51));
        DeleteGroupBtn.setText("DELETE GROUP");
        DeleteGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteGroupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GroupPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(DeletePostBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(ViewPostBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(EditPostBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(AddPostBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                    .addComponent(LeaveGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(DeleteGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ViewProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RemoveMemberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PromoteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DemoteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresshBtn)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(refresshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GroupPhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(DeleteGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditPostBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddPostBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeletePostBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewPostBtn)
                                    .addComponent(LeaveGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DemoteMember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PromoteMember)
                                .addGap(18, 18, 18)
                                .addComponent(RemoveMemberBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ViewProf)
                                .addGap(54, 54, 54))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPostBtnActionPerformed
        // TODO add your handling code here:
        AddPostToGroup addPostToGroup=new AddPostToGroup(group);
        this.setVisible(false);
        addPostToGroup.setVisible(true);
    }//GEN-LAST:event_AddPostBtnActionPerformed

    private void LeaveGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveGroupActionPerformed
        // TODO add your handling code here:
        leaveGroup(group.getGroupId(),LoginScreen.activeUser.getUserId());
        Groups g=new Groups();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LeaveGroupActionPerformed

    private void ViewPostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPostBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Post> posts=group.getPosts();
        int index = GroupPostsList.getSelectedIndex();
        Post p=posts.get(index);
        ViewPost viewPost = new ViewPost(p);
        viewPost.setVisible(true);
    }//GEN-LAST:event_ViewPostBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Groups g=new Groups();
        g.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void RemoveMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMemberBtnActionPerformed
        // TODO add your handling code here:
        removeUserFromGroup(group.getGroupId(),LoginScreen.activeUser.getUserId(),GroupMembersList.getSelectedValue());
    }//GEN-LAST:event_RemoveMemberBtnActionPerformed

    private void refresshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresshBtnActionPerformed
        // TODO add your handling code here:
        GroupName.setText(group.getGroupName());

        // Update the group photo
        String path = group.getPhotoPath();
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(230, 88, Image.SCALE_DEFAULT);
        GroupPhotoLabel.setIcon(new ImageIcon(scaledImg));

        // Update the list of group posts
        ArrayList<Post> posts = group.getPosts();
        DefaultListModel<String> postListModel = new DefaultListModel<>();
        for (Post post : posts) {
            postListModel.addElement(post.getContent());
        }
        GroupPostsList.setModel(postListModel);

        // Update the list of group members
        ArrayList<String> members = group.getUserIds();
        DefaultListModel<String> memberListModel = new DefaultListModel<>();
        for (String member : members) {
            memberListModel.addElement(member);
        }
        GroupMembersList.setModel(memberListModel);
    this.repaint();

    }//GEN-LAST:event_refresshBtnActionPerformed

    private void DeletePostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePostBtnActionPerformed
        // TODO add your handling code here:
        String s=GroupPostsList.getSelectedValue();
        ArrayList<Post> p=group.getPosts();
        String id=null;
        for (Post post : p) {
            if(s.equals(post.getContent()))
            id=post.getContentId();
        }
        removePostFromGroup(group.getGroupId(),LoginScreen.activeUser.getUserId(),id);
    }//GEN-LAST:event_DeletePostBtnActionPerformed

    private void EditPostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPostBtnActionPerformed
        // TODO add your handling code here:
        String s=GroupPostsList.getSelectedValue();
        ArrayList<Post> p=group.getPosts();
        String id=null;
        for (Post post : p) {
            if(s.equals(post.getContent()))
            id=post.getContentId();
        }
        String s2=JOptionPane.showInputDialog("enter the new content");
        editGroupPost(group.getGroupId(),LoginScreen.activeUser.getUserId(),id, s2);
    }//GEN-LAST:event_EditPostBtnActionPerformed

    private void ViewProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfActionPerformed
        // TODO add your handling code here:
        User l=null;
        String name=GroupMembersList.getSelectedValue();
        ArrayList<User> users=User.loadUsers();
        for (User user : users) {
            if(name.equals(user.getUsername())){
                l=user;
                break;
            }
        }
        viewProfile p=new viewProfile(l);
        p.setVisible(true);
    }//GEN-LAST:event_ViewProfActionPerformed

    private void PromoteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoteMemberActionPerformed
        // TODO add your handling code here:
        promoteToAdmin(group.getGroupId(),LoginScreen.activeUser.getUserId(),GroupMembersList.getSelectedValue());
        updateData();
    }//GEN-LAST:event_PromoteMemberActionPerformed

    private void DemoteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoteMemberActionPerformed
        // TODO add your handling code here:
        demoteFromAdmin(group.getGroupId(),LoginScreen.activeUser.getUserId(),GroupMembersList.getSelectedValue());
    }//GEN-LAST:event_DemoteMemberActionPerformed

    private void DeleteGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteGroupBtnActionPerformed
        // TODO add your handling code here:
        deleteGroup(group.getGroupId(),LoginScreen.activeUser.getUserId());
        Groups g=new Groups();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeleteGroupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatorGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatorGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatorGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatorGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatorGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPostBtn;
    private javax.swing.JButton DeleteGroupBtn;
    private javax.swing.JButton DeletePostBtn;
    private javax.swing.JButton DemoteMember;
    private javax.swing.JButton EditPostBtn;
    private javax.swing.JList<String> GroupMembersList;
    private javax.swing.JLabel GroupName;
    private javax.swing.JLabel GroupPhotoLabel;
    private javax.swing.JList<String> GroupPostsList;
    private javax.swing.JButton LeaveGroup;
    private javax.swing.JButton PromoteMember;
    private javax.swing.JButton RemoveMemberBtn;
    private javax.swing.JButton ViewPostBtn;
    private javax.swing.JButton ViewProf;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton refresshBtn;
    // End of variables declaration//GEN-END:variables
}
