/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab99;

import static com.mycompany.lab99.BlockedFriends.blockFriend;
import static com.mycompany.lab99.BlockedFriends.unblockFriend;
import static com.mycompany.lab99.FriendContent.getFriendPosts;
import static com.mycompany.lab99.FriendContent.getFriendStories;
import static com.mycompany.lab99.FriendRequest.sendRequest;
import static com.mycompany.lab99.Friends.removeFriendship;
import static com.mycompany.lab99.Friends.search;
import static com.mycompany.lab99.Friends.suggestFriends;
import static com.mycompany.lab99.Friends.viewRequestSenders;
import static com.mycompany.lab99.Group.suggestGroups;
import static com.mycompany.lab99.RequestNotifications.UserRequestsNotifications;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Victus
 */
public class NewsFeed extends javax.swing.JFrame {

    /**
     * Creates new form NewsFeed
     */
    public NewsFeed() {
        initComponents();
                DefaultListModel<String> SuggestGroups = new DefaultListModel<>();
ArrayList<Group> g=suggestGroups(LoginScreen.activeUser.getUserId());
        for (Group group : g) {
            SuggestGroups.addElement(group.getGroupName());
        }
        SuggestGroupsList.setModel(SuggestGroups);
        DefaultListModel<String> listModel2 = new DefaultListModel<>();
        ArrayList<Post> posts = getFriendPosts(LoginScreen.activeUser.getUserId());
        for (Post post : posts) {
            listModel2.addElement(post.getContent());

        }
        FriendsPostsList.setModel(listModel2);
        DefaultListModel<String> listModel3 = new DefaultListModel<>();
        Story.deleteStories();

        ArrayList<Story> stories = getFriendStories(LoginScreen.activeUser.getUserId());
        for (Story story : stories) {
            listModel3.addElement(story.getContent());
        }
        FriendsStoriesList.setModel(listModel3);
        DefaultListModel<String> listModel4 = new DefaultListModel<>();
        ArrayList<User> suggests = suggestFriends(LoginScreen.activeUser.getUserId());
        for (User suggest : suggests) {
            listModel4.addElement(suggest.getUserId());
        }
        SuggestList.setModel(listModel4);

        DefaultListModel<String> listModel5 = new DefaultListModel<>();
        ArrayList<RequestNotifications> requestnotifications = UserRequestsNotifications(LoginScreen.activeUser.getUserId());
        for (RequestNotifications notification : requestnotifications) {
            listModel5.addElement(notification.getMessage());
        }
        notificationsList.setModel(listModel5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToProfileBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        FriendsPostsList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        FriendsStoriesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ViewPostBtn = new javax.swing.JButton();
        ViewStoryBtn1 = new javax.swing.JButton();
        idText = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        AddFriendBtn = new javax.swing.JButton();
        refresh2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        SuggestList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        AddSuggest = new javax.swing.JButton();
        UnblockBtn = new javax.swing.JButton();
        blockButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        GroupsBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        viewNotificationButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        notificationsList = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        SuggestGroupsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        joinGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackToProfileBtn.setBackground(new java.awt.Color(102, 255, 153));
        BackToProfileBtn.setText("Back to profile page");
        BackToProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToProfileBtnActionPerformed(evt);
            }
        });

        FriendsPostsList.setBackground(new java.awt.Color(255, 51, 204));
        FriendsPostsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(FriendsPostsList);

        FriendsStoriesList.setBackground(new java.awt.Color(255, 51, 204));
        FriendsStoriesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(FriendsStoriesList);

        jLabel2.setText("Friends posts");

        jLabel3.setText("Friends stories");

        ViewPostBtn.setBackground(new java.awt.Color(255, 204, 204));
        ViewPostBtn.setText("View post");
        ViewPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPostBtnActionPerformed(evt);
            }
        });

        ViewStoryBtn1.setBackground(new java.awt.Color(255, 204, 204));
        ViewStoryBtn1.setText("View story");
        ViewStoryBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStoryBtn1ActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        searchList.setBackground(new java.awt.Color(255, 51, 204));
        jScrollPane6.setViewportView(searchList);

        AddFriendBtn.setBackground(new java.awt.Color(255, 204, 204));
        AddFriendBtn.setText("Add friend");
        AddFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFriendBtnActionPerformed(evt);
            }
        });

        refresh2.setText("refresh");
        refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2ActionPerformed(evt);
            }
        });

        SuggestList.setBackground(new java.awt.Color(255, 51, 204));
        jScrollPane7.setViewportView(SuggestList);

        jLabel4.setText("Suggest Friends:");

        AddSuggest.setBackground(new java.awt.Color(255, 204, 204));
        AddSuggest.setText("Add friend");
        AddSuggest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSuggestActionPerformed(evt);
            }
        });

        UnblockBtn.setBackground(new java.awt.Color(255, 204, 204));
        UnblockBtn.setText("Unblock");
        UnblockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnblockBtnActionPerformed(evt);
            }
        });

        blockButton.setBackground(new java.awt.Color(255, 204, 204));
        blockButton.setText("Block");
        blockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 204, 204));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        viewProfileButton.setBackground(new java.awt.Color(255, 204, 204));
        viewProfileButton.setText("View profile");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });

        GroupsBtn.setBackground(new java.awt.Color(51, 51, 255));
        GroupsBtn.setText("Groups");
        GroupsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupsBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Notifications");

        viewNotificationButton.setBackground(new java.awt.Color(255, 204, 204));
        viewNotificationButton.setText("View notification");
        viewNotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNotificationButtonActionPerformed(evt);
            }
        });

        notificationsList.setBackground(new java.awt.Color(255, 51, 204));
        notificationsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(notificationsList);

        SuggestGroupsList.setBackground(new java.awt.Color(255, 51, 204));
        SuggestGroupsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(SuggestGroupsList);

        jLabel1.setText("Suggest Groups:");

        joinGroup.setBackground(new java.awt.Color(255, 204, 204));
        joinGroup.setText("Join group");
        joinGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refresh2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(AddSuggest, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GroupsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(viewNotificationButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UnblockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchBtn)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinGroup))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ViewPostBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewStoryBtn1)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackToProfileBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchBtn)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refresh2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GroupsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(AddSuggest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(viewProfileButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(blockButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UnblockBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddFriendBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(joinGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewPostBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ViewStoryBtn1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewNotificationButton)
                        .addGap(89, 89, 89))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToProfileBtnActionPerformed
        // TODO add your handling code here:'
        ProfilePage profilePage = new ProfilePage(LoginScreen.activeUser);
        profilePage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToProfileBtnActionPerformed

    private void ViewPostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPostBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Post> posts2 = getFriendPosts(LoginScreen.activeUser.getUserId());
        int index = FriendsPostsList.getSelectedIndex();
        Post p = posts2.get(index);
        ViewPost viewPost = new ViewPost(p);
        viewPost.setVisible(true);
    }//GEN-LAST:event_ViewPostBtnActionPerformed

    private void ViewStoryBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStoryBtn1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Story> story2 = getFriendStories(LoginScreen.activeUser.getUserId());
        int index = FriendsStoriesList.getSelectedIndex();
        Story s = story2.get(index);
        ViewStory viewStory = new ViewStory(s);
        viewStory.setVisible(true);
    }//GEN-LAST:event_ViewStoryBtn1ActionPerformed

    private void AddFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFriendBtnActionPerformed
        // TODO add your handling code here:
        User l = null;
        String s = searchList.getSelectedValue();
        ArrayList<User> A = User.loadUsers();
        for (User user : A) {
            if (s.equals(user.getUsername())) {
                l = user;
                break;
            }
        }
        sendRequest(LoginScreen.activeUser.getUserId(), l.getUserId());
//           JOptionPane.showMessageDialog(this, "request sent", "request", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_AddFriendBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<User> a = search(idText.getText());
        DefaultListModel<String> listModel2 = new DefaultListModel<>();
        for (User user : a) {
            listModel2.addElement(user.getUsername());
        }
        searchList.setModel(listModel2);

    }//GEN-LAST:event_SearchBtnActionPerformed

    private void refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2ActionPerformed
        // TODO add your handling code here:
                DefaultListModel<String> SuggestG = new DefaultListModel<>();
ArrayList<Group> g=suggestGroups(LoginScreen.activeUser.getUserId());
        for (Group group : g) {
            SuggestG.addElement(group.getGroupName());
        }
SuggestGroupsList.setModel(SuggestG);
        // Refresh Friend Posts
        DefaultListModel<String> postsModel = new DefaultListModel<>();
        ArrayList<Post> friendPosts = getFriendPosts(LoginScreen.activeUser.getUserId());
        for (Post post : friendPosts) {
            postsModel.addElement(post.getContent());
        }
        FriendsPostsList.setModel(postsModel);

        // Refresh Friend Stories
        DefaultListModel<String> storiesModel = new DefaultListModel<>();
        Story.deleteStories(); // Ensure expired stories are removed
        ArrayList<Story> friendStories = getFriendStories(LoginScreen.activeUser.getUserId());
        for (Story story : friendStories) {
            storiesModel.addElement(story.getContent());
        }
        FriendsStoriesList.setModel(storiesModel);

        DefaultListModel<String> listModel5 = new DefaultListModel<>();
        ArrayList<RequestNotifications> requestnotifications = UserRequestsNotifications(LoginScreen.activeUser.getUserId());
        for (RequestNotifications notification : requestnotifications) {
            listModel5.addElement(notification.getMessage());
        }
        notificationsList.setModel(listModel5);
    }//GEN-LAST:event_refresh2ActionPerformed

    private void AddSuggestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSuggestActionPerformed
        // TODO add your handling code here:
        String s = SuggestList.getSelectedValue();

        sendRequest(LoginScreen.activeUser.getUserId(), s);
    }//GEN-LAST:event_AddSuggestActionPerformed

    private void UnblockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnblockBtnActionPerformed
        // TODO add your handling code here:
        String f = searchList.getSelectedValue();
        unblockFriend(LoginScreen.activeUser.getUserId(), f);
        JOptionPane.showMessageDialog(this, "Unblocked");
    }//GEN-LAST:event_UnblockBtnActionPerformed

    private void blockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButtonActionPerformed
        //block friend
        String f=searchList.getSelectedValue();
        String f1=f.split(" ")[0];
        blockFriend(LoginScreen.activeUser.getUserId(),f1);
        JOptionPane.showMessageDialog(this, "blocked");
    }//GEN-LAST:event_blockButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //remove friend
        String f=searchList.getSelectedValue();
        String f1=f.split(" ")[0];
        removeFriendship(LoginScreen.activeUser.getUserId(),f1);
        JOptionPane.showMessageDialog(this, "removed");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
        User l = null;
        String s = searchList.getSelectedValue();
        ArrayList<User> A = User.loadUsers();
        for (User user : A) {
            if (s.equals(user.getUsername())) {
                l = user;
                break;
            }
        }

        viewProfile viewprofile = new viewProfile(l);
        viewprofile.setVisible(true);
    }//GEN-LAST:event_viewProfileButtonActionPerformed

    private void GroupsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupsBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Groups groups=new Groups();
        groups.setVisible(true);
    }//GEN-LAST:event_GroupsBtnActionPerformed

    private void viewNotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNotificationButtonActionPerformed
        String message=notificationsList.getSelectedValue();
        
        //
        if(message.contains("request")){
            //notification is a friend request
                       
            //create a friend request page
            FriendRequestPage friendrequestpage=new FriendRequestPage(message);
            friendrequestpage.setVisible(true);
        
        }
    }//GEN-LAST:event_viewNotificationButtonActionPerformed

    private void joinGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGroupActionPerformed
        // TODO add your handling code here:
        Group l=null;
String s=SuggestGroupsList.getSelectedValue();
ArrayList<Group> groups=Group.loadGroups();
        for (Group group : groups) {
            if(s.equals(group.getGroupName())){
            l=group;
            break;
            }
        }
        Group.addToGroup(l.getGroupId(), LoginScreen.activeUser.getUserId());

    }//GEN-LAST:event_joinGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsFeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsFeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsFeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsFeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewsFeed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFriendBtn;
    private javax.swing.JButton AddSuggest;
    private javax.swing.JButton BackToProfileBtn;
    private javax.swing.JList<String> FriendsPostsList;
    private javax.swing.JList<String> FriendsStoriesList;
    private javax.swing.JButton GroupsBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JList<String> SuggestGroupsList;
    private javax.swing.JList<String> SuggestList;
    private javax.swing.JButton UnblockBtn;
    private javax.swing.JButton ViewPostBtn;
    private javax.swing.JButton ViewStoryBtn1;
    private javax.swing.JButton blockButton;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton joinGroup;
    private javax.swing.JList<String> notificationsList;
    private javax.swing.JButton refresh2;
    private javax.swing.JButton removeButton;
    private javax.swing.JList<String> searchList;
    private javax.swing.JButton viewNotificationButton;
    private javax.swing.JButton viewProfileButton;
    // End of variables declaration//GEN-END:variables
}
